num1=int(input("შემოიყვანე რიცხვი"))
num2=int(input("შემოიყვანე მეორე რიცხვი"))
print(num1 +num2)
print(num1/num2)
print(num1*num2)    
name=input("enter your name")
surname=input("enter your surname")
age=int(input("your age"))          
print("ჩემი სახელი" + name + "Cemi gvari aris" + surname + "ჩემი ასაკი არის " + age) 